stages:
  - build
  - push
  - commit

variables:
  DOCKER_REGISTRY: $CI_REGISTRY
  DOCKER_REGISTRY_USER: $CI_REGISTRY_USER
  DOCKER_REGISTRY_PASSWORD: $CI_REGISTRY_PASSWORD

.default-job-template: &default-job-template
  before_script:
    - echo $DOCKER_REGISTRY_PASSWORD | docker login -u $DOCKER_REGISTRY_USER --password-stdin $DOCKER_REGISTRY
  script:
    - docker build -t $DOCKER_REGISTRY/$SERVICE_NAME:$CI_COMMIT_SHORT_SHA apps/$SERVICE_NAME
    - docker push $DOCKER_REGISTRY/$SERVICE_NAME:$CI_COMMIT_SHORT_SHA
    # Update Helm values.yaml
    - sed -i "s|tag:.*|tag: $CI_COMMIT_SHORT_SHA|" charts/$SERVICE_NAME/values.yaml
  artifacts:
    paths:
      - "charts/$SERVICE_NAME/values.yaml"
  only:
    - main

user-service:
  stage: build
  variables:
    SERVICE_NAME: "user-service"
  <<: *default-job-template

order-service:
  stage: build
  variables:
    SERVICE_NAME: "order-service"
  <<: *default-job-template

payment-service:
  stage: build
  variables:
    SERVICE_NAME: "payment-service"
  <<: *default-job-template

inventory-service:
  stage: build
  variables:
    SERVICE_NAME: "inventory-service"
  <<: *default-job-template

commit-updated-tags:
  stage: commit
  script:
    - git config --global user.name "GitLab CI"
    - git config --global user.email "ci@gitlab.com"
    - git add charts/*/values.yaml
    - git commit -m "ci: update image tags to $CI_COMMIT_SHORT_SHA [skip ci]" || echo "No changes to commit"
    - git push origin $CI_COMMIT_REF_NAME
  only:
    - main
