stages:
  - build
  - push

variables:
  DOCKER_REGISTRY: docker.io
  DOCKER_USERNAME: "sushilg"
  DOCKER_PASSWORD: "Mojo#11#11"
  DOCKER_IMAGE_PREFIX: "sgunjekar"

.build-template: &build-template
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin $DOCKER_REGISTRY

order-service:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    SERVICE_NAME: "order-service"
    IMAGE_TAG: "order-service-latest"
  <<: *build-template
  script:
    - docker build -t $DOCKER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE_PREFIX:$IMAGE_TAG apps/$SERVICE_NAME

push-order-service:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  variables:
    IMAGE_TAG: "order-service-latest"
  <<: *build-template
  script:
    - docker push $DOCKER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE_PREFIX:$IMAGE_TAG

payment-service:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    SERVICE_NAME: "payment-service"
    IMAGE_TAG: "payment-service-latest"
  <<: *build-template
  script:
    - docker build -t $DOCKER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE_PREFIX:$IMAGE_TAG apps/$SERVICE_NAME

push-payment-service:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  variables:
    IMAGE_TAG: "payment-service-latest"
  <<: *build-template
  script:
    - docker push $DOCKER_REGISTRY/$DOCKER_USERNAME/$DOCKER_IMAGE_PREFIX:$IMAGE_TAG
