stages:
  - build

variables:
  DOCKER_REGISTRY: docker.io
  DOCKER_USERNAME: "sushilg"
  DOCKER_PASSWORD: "Mojo#11#11"
  DOCKER_IMAGE_PREFIX: "sgunjekar"

.build-and-push: &build-and-push
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin $DOCKER_REGISTRY

order-service:
  stage: build
  variables:
    SERVICE_NAME: "order-service"
    IMAGE_NAME: "sgunjekar/order-service:latest"
    REMOTE_IMAGE_TAG: "sushilg/sgunjekar:order-service-latest"
  <<: *build-and-push
  script:
    - cd apps/$SERVICE_NAME
    - docker build -t $IMAGE_NAME .
    - docker tag $IMAGE_NAME $REMOTE_IMAGE_TAG
    - docker push $REMOTE_IMAGE_TAG

inventory-service:
  stage: build
  variables:
    SERVICE_NAME: "inventory-service"
    IMAGE_NAME: "sgunjekar/inventory-service:latest"
    REMOTE_IMAGE_TAG: "sushilg/sgunjekar:inventory-service-latest"
  <<: *build-and-push
  script:
    - cd apps/$SERVICE_NAME
    - docker build -t $IMAGE_NAME .
    - docker tag $IMAGE_NAME $REMOTE_IMAGE_TAG
    - docker push $REMOTE_IMAGE_TAG

user-service:
  stage: build
  variables:
    SERVICE_NAME: "user-service"
    IMAGE_NAME: "sgunjekar/user-service:latest"
    REMOTE_IMAGE_TAG: "sushilg/sgunjekar:user-service-latest"
  <<: *build-and-push
  script:
    - cd apps/$SERVICE_NAME
    - docker build -t $IMAGE_NAME .
    - docker tag $IMAGE_NAME $REMOTE_IMAGE_TAG
    - docker push $REMOTE_IMAGE_TAG

payment-service:
  stage: build
  variables:
    SERVICE_NAME: "payment-service"
    IMAGE_NAME: "sgunjekar/payment-service:latest"
    REMOTE_IMAGE_TAG: "sushilg/sgunjekar:payment-service-latest"
  <<: *build-and-push
  script:
    - cd apps/$SERVICE_NAME
    - docker build -t $IMAGE_NAME .
    - docker tag $IMAGE_NAME $REMOTE_IMAGE_TAG
    - docker push $REMOTE_IMAGE_TAG
