apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: otel-collector
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["--config=/etc/otel-collector/config.yaml"]
          volumeMounts:
            - name: config-volume
              mountPath: /etc/otel-collector
              readOnly: true
          ports:
            - containerPort: 4317
      volumes:
        - name: config-volume
          configMap:
            name: otel-collector-config

